debugs:
    debug: True 

data:
    valSplitPercen: .2 #20% of the data for validation
    dataPath: "../TestData"
    test: "Test_2" #One person fixed pace, straight path, has labels
    #test: "Test_3" #One person, down hall, into and around lab, has labels, 
    #test: "Test_4" #Multiple people variyed pace, no labels

    sensorList: [8, 7, 6, 5, 4, 3, 2, 12, 1] # Test 2
    #sensorList: [6, 5, 4, 3, 2, 1, 10, 9, 11, 12, 13] # test 3

    windowLen: 2 #sec
    stepSize: 1 #sec

trainer:
    #criterion: "Huber"
    criterion: "CrossEntropyLoss"
    #criterion: "MSE"
    optimizer: "Adam"
    #optimizer: "SGD"
    learning_rate: 0.0001
    weight_decay: 0.00001
    epochs: 1 # 20

model: 
    name: "leNetV5"
    #name: "multilayerPerceptron"

    multilayerPerceptron:
        hidden_neurons: 100

    leNetV5:
        hidden_neurons: 100