%% ─────────────────────────────────────────────
%% 📈 HOW TO PREVIEW THIS DIAGRAM:
%% → Right-click this file tab (not the content) → “Command Palette”
%% → Type: “Preview Mermaid Diagram”
%% ─────────────────────────────────────────────
graph TD
    classDef done fill:#004d00,stroke:#00ff00,color:#ffffff;
    classDef inprogress fill:#333300,stroke:#ffff66,color:#ffffff;
    classDef pending fill:#4d0000,stroke:#ff6666,color:#ffffff;
    classDef shared fill:#2f2f2f,stroke:#cccccc,color:#ffffff;

    A[Acquire Funding]

    %% Sensor Instalation
    A --> B1[Sensor Hardware Install]
    A --> B2[Data Acquisition Install]
    A --> B3[Camera Install]
    class A done;
    class B1 done;
    class B2 done;
    class B3 done;

    %% Data acquistion, Walking Pace Tagged
    subgraph First pass data Caputure
        C1[Label Walking Pace with ADPM wearable BioSensor System]
        C2[Capture Labled Data]
    end
    C1 --> C2
    B1 --> C2
    B2 --> C2
    class C1 done;
    class C2 done;

    %% Footstep Wavelet
    subgraph FootStep Wavelet
        D1[Footstep Wavelet]
    end
    D1 --> E1
    class D1 done;


    %% Model Development, data transform
    C2 --> E1
    subgraph Josh ENGR 897: Compairson of Wavlet Transformed Data with MobilNet
        E1[CWT Transform of Data]
        class E1 done;
        E2[Data Loader]
        class E2 done;
        E3[Data Norm]
        class E3 done;
        E4[Build Model]
        class E4 done;
        E5[Train On Time Domain]
        class E5 done;
        E6[Train On Wavelet Domain]
        class E6 done;
        E7[Train On Spectra Domain]
        class E7 done;
        E8[Compair Results]
        class E8 inprogress;
    end
    E1 --> E2
    E2 --> E3
    E3 --> E4
    E4 --> E5
    E4 --> E6
    E4 --> E7
    E5-->E8
    E6-->E8
    E7-->E8

    %% Using Camera to label data
    B2 --> Ga1
    B3 --> Ga2
    subgraph STARS 2025: Demonstrat Data Labeling with Camera
        Ga1[Modify Vib to Save Trigger Time]
        class Ga1 done;
        Ga2[Set Up Camera System]
        class Ga2 done;
        G1[Capture Vib Data]
        class G1 done;
        G2[Capture Camera Data]
        class G2 done;
        G3[Calibrate Halway Position y-->Z]
        class G3 done;
        G4[Pose Estimation]
        class G4 inprogress;
        G5[Calculate Waking Speed]
        class G5 inprogress;
        G6[Time Sync Data]
        class G6 inprogress;
    end
    Ga1 -->G1
    Ga2 -->G2
    G2 --> G4
    G2 --> G3
    G1 --> G6
    G5 --> G6
    G3 --> G5
    G4 --> G5

    G3 --> I2
    G3 --> I3
    %% From footstep wavelet
    D1 --> I4 
    E8 --> I1 
    D1 --> I1 
    E8 --> I5 
    subgraph Math: Fall 2025
        I1[filter]
        I2[X Location]
        I3[X, Z Location with camera move]
        I4[Complex Version of FootStep Wavelet]
        I5[Complex Models]
    end


    E8 --> J1
    subgraph Josh ENGR 898: Federated Learning
        J1[Research Fed Learn]
        J99
    end
    J1 --> J99

    G6 --> K1
    subgraph FootStep Features
        K1[Use Object detection: e.x. YOLO]
    end

    I2 -->L1
    G6 --> L1
    subgraph Stride Features
        L1[Use Transformer]
    end

    %% Unphased issues

    %% Fin
    J99 --> Z
    L1 --> Z
    K1 --> Z
    Z[Real Time Prediction of Health from Gait]

    class Z shared;