%% ─────────────────────────────────────────────
%% 📈 HOW TO PREVIEW THIS DIAGRAM:
%% → Right-click this file tab (not the content) → “Command Palette”
%% → Type: “Preview Mermaid Diagram”
%% Mac:           CMD  + Shift + P
%% Linux/Windows: Ctrl + Shift + P
%% ─────────────────────────────────────────────
graph TD
    classDef done fill:#004d00,stroke:#00ff00,color:#ffffff;
    classDef pending fill:#4d0000,stroke:#ff6666,color:#ffffff;
    classDef inprogress fill:#333300,stroke:#ffff66,color:#ffffff;

    A[Acquire Funding]

    %% Sensor Instalation
    A --> B1[Sensor Hardware Install]
    B1 --> B2[Data Acquisition Install]
    A --> B3[Camera Install]
    class A done;
    class B1 done;
    class B2 done;
    class B3 done;

    %% Data acquistion, Walking Pace Tagged
    subgraph sg_C[First pass data Caputure]
        C1[Label Walking Pace with ADPM wearable BioSensor System]
        C2[Capture Labled Data]
    end
    C1 --> C2
    B2 --> C2
    class C1 done;
    class C2 done;


    %% Footstep Wavelet
    subgraph sg_d[FootStep Wavelet]
        D1[Footstep Wavelet]
        class D1 done;
        D1 --> sd_d1
        subgraph sd_d1[Complex Footstep Wavelet]
            direction TB
            d1_0[Complex version of footstep wavelet: DD]
            class d1_0 inprogress;
            d1_1[computation of complex footstep wavelet transform]
            class d1_1 done;
            d1_0 --> d1_1
        end
    end
    sg_d --> E1


    %% Model Development, data transform
    C2 --> E1
    subgraph Josh ENGR 897: Compairson of Wavlet Transformed Data with MobilNet
        E1[CWT Transform of Data]
        class E1 done;
        E2[Data Loader]
        class E2 done;
        E3[Data Norm]
        class E3 done;
        E4[Build Model]
        class E4 done;
        E5[Train On Time Domain]
        class E5 done;
        E6[Train On Wavelet Domain]
        class E6 done;
        E7[Train On Spectra Domain]
        class E7 done;
        E8[Compair Results]
        class E8 inprogress;
    end
    E1 --> E2
    E2 --> E3
    E3 --> E4
    E4 --> E5
    E4 --> E6
    E4 --> E7
    E5-->E8
    E6-->E8
    E7-->E8


    %% Using Camera to label data
    %%E2 --> F1
    B2 --> G1
    B3 --> G2
    subgraph STARS 2025: Demonstrat Data Labeling with Camera
        G1[Timestamp Vib Data]
        class G1 done;
        G2[Timestamp Camera]
        class G2 done;
        H1[Capture Vib Data]
        class H1 done;
        H2[Capture Camera Data]
        class H2 done;
        H4[Anonymize Video]
        class H4 done;
        H10[Get Video Time]
        class H10 done;
        H3[Calibrate Camera Hall Distance: y -> Z]
        class H3 done;
        H5[Pose Estimation]
        class H5 done;
        H6[Track Walker]
        class H6 done;
        H9[Calculate Speed]
        class H9 inprogress;
        H7[Time Sync Data]
        class H7 inprogress;
        H8[Label Vib Data from Camera]
        class H8 inprogress;
    end
    G1 --> H1
    G2 --> H2
    H1 --> H7
    H2 --> H4
    H2 --> H5
    H2 --> H3
    H2 --> H10
    H10 --> H7
    H5 --> H6
    H3 --> H9
    H6 --> H9
    H9 --> H7
    H7 --> H8

    subgraph sg_i[Locate Footsteps]

        subgraph sg-i1[Closed Form Solution X, Y - Raphael]
            sg-i1-0[Research Closed Form]
            sg-i1-1[load data]
            sg-i1-2[Implement Closed Form]
        end

        subgraph sg-i2[From camera]
            sg-i2-1[x -> X Location:Duy]
            sg-i2-2[x -> X Location:Mihir]
            sg-i2-1 --> sg-i2-2
            class sg-i2-1 inprogress
            class sg-i2-2 inprogress
        end

        subgraph sg-i3[From Pose Estimation]
        end

        subgraph sg-i4[From CVCNN]
        end
    end
    SG_M --> sg-i4
    H3 --> sg_i
    sg_i --> I3

    %% From footstep wavelet
    sg_d --> I1 
    sg_d --> sd_d1
    sg_d --> I8
    subgraph Math: 
        I1[Filter]
        I3[X, Z Location with camera move]
        I6[Identify Footsteps]
        I7[Multi-Footstep]
        I8[Improve FootStep Wavelet]
        I9[Investigate wavelet f0 and bw]
    end
    sg_d --> sd_d1 --> SG_M
    I6 --> I7

    H8 --> J1
    E8 --> J1


    subgraph Federated Learning - Pareshbhai
        J1[Research Fed Learn]
        class J1 inprogress;
        J2[Load Data to Sensor Clusters]
        J3[Window By Cluster]
        J4[Train on One Cluster]
        J5[Validate with another clusters Data]
        J_4[Fed Train]
        J_5[Validate]
        J99[Compair Fed to Non Fed]
    end
    J1 --> J2
    J2 --> J3
    J3 --> J4
    J4 --> J5
    J3 --> J_4
    J_4 --> J_5

    J5 --> J99
    J_5 --> J99

    H8 --> K0
    I1 --> K1
    I7 --> K1
    I8 --> K1
    subgraph FootStep Features
        K0[Label Footsteps]
        K1[Use Object detection: e.x. YOLO, SSD]
        K99[Output Footstep Features]
    end
    K0 --> K1
    K1 --> K99

    sg_i -->L1
    M99 --> L1
    I8 --> L99
    subgraph Stride Features
        L1[Label Stride Features]
        L99[Use Transformer?]
    end
    L1 --> L99

    E8 --> SG_M
    sg_i --> SG_M
    subgraph SG_M[Complex CNNs]
        M0[Complex Models in pyTorch]
        class M0 done;
        M1[Research Complex Models]
        class M1 inprogress;
        M2[Load Complex Data to DataLoader]
        class M2 done;

        M3[Conv]
        class M3 done;
        M4[Activation Function]
        class M4 inprogress;
        M5[Pool]
        class M5 inprogress;
        M6[Norm]
        class M6 inprogress;

        M10[Real/Image Seperate Layers]
        M11[Mag/phase Seperate Layers]
        M12[Full Real/Imag]
        M13[Full Mag/Phase]

        M20[Complex LeNet]
        class M20 done;
        M21[Complex VGG]
        class M21 done;


        M40[experiment with Complex]

        M99[Compair Complex Results]
    end
    M0 --> M1
    M1 --> M2

    sg_d --> M2

    M2 --> M3
    M2 --> M4
    M2 --> M5
    M2 --> M6
    M3 --> M20
    M4 --> M20
    M5 --> M20
    M6 --> M20
    M20 --> M21

    M21 --> M40

    M4 --> M40
    M5 --> M40
    M6 --> M40
    M10 --> M40
    M11 --> M40
    M12 --> M40
    M13 --> M40

    M40 --> M99



    %% Unphased issues
    I3 --> X1[Camera Track Walker]
    H4 --> X2[Anonymizeon on Camera]
    H5 --> X3[Invstigate Pose-Est Packages]
    H3 --> X9[Sterio Camera]
    H7 --> X4[Real Time Camera]

    %% End Prodcut
    J99 --> Z
    L99 --> Z
    K99 --> Z
    Z[Real Time Prediction of Health from Gait]

    class Z shared;