%% ─────────────────────────────────────────────
%% 📈 HOW TO PREVIEW THIS DIAGRAM:
%% → Right-click this file tab (not the content) → “Command Palette”
%% → Type: “Preview Mermaid Diagram”
%% ─────────────────────────────────────────────
graph TD
    classDef done fill:#004d00,stroke:#00ff00,color:#ffffff;
    classDef inprogress fill:#333300,stroke:#ffff66,color:#ffffff;
    classDef pending fill:#4d0000,stroke:#ff6666,color:#ffffff;
    classDef shared fill:#2f2f2f,stroke:#cccccc,color:#ffffff;

    A[Acquire Funding]

    %% Phase 1 - Sensor Instalation
    A --> B1[Sensor Hardware Install]
    A --> B2[Data Acquisition Install]
    A --> B3[Camera Install]
    class A done;
    class B1 done;
    class B2 done;
    class B3 done;

    %% Phase 2 - Data acquistion, Walking Pace Tagged
    subgraph First pass data Caputure
    C2
    C1
    end
    C1[Label Walking Pase with ADPM wearable BioSensor System]
    C1 --> C2
    B1 --> C2[Capture Labled Data]
    B2 --> C2
    class C1 done;
    class C2 done;

    %% Phase 2 - Footstep Wavelet
    subgraph FootStep Wavelet
    D
    end
    D[Footstep Wavelet]
    D --> E1
    class D done;


    subgraph Josh ENGR 897: Compairson of Wavlet Transformed Data with MobilNet
     E1
     E2
     E3
     F1
    end
    %% Phase 4 - Model Development, data transform
    C2 --> E1[Signal Preprocessing]
    class E1 done;
    E1 --> E2[Model Architecture Design]
    class E2 done;
    E1 --> E3[Labeling & Feature Engineering]
    class E3 done;
    E3 --> F1[Model Training]
    class F1 inprogress;

    %% Phase 5 - Training & Evaluation
    E2 --> F1
    B2 --> G1
    B3 --> G2
    subgraph STARS 2025: Demonstrat Data Labeling with Camera
        G1[Timestamp Vib Data]
        class G1 done;
        G2[Timestamp Camera]
        class G2 done;
        H1[Capture Vib Data]
        class H1 done;
        H2[Capture Camera Data]
        class H2 done;
        H4[Anonymize Video]
        class H4 inprogress;
        H10[Get Video Time]
        class H10 inprogress;
        H3[Calibrate Camera Hall Distance: Z]
        class H3 done;
        H5[Pose Estimation]
        class H5 done;
        H6[Track Walker]
        class H6 inprogress;
        H9[Calculate Speed]
        class H9 inprogress;
        H7[Time Sync Data]
        class H7 inprogress;
        H8[Label Vib Data from Camera]
        class H8 pending;
    end
    G1 --> H1
    G2 --> H2
    H1 --> H7
    H2 --> H4
    H2 --> H5
    H2 --> H3
    H2 --> H10
    H10 --> H7
    H5 --> H6
    H3 --> H9
    H6 --> H9
    H9 --> H7
    H7 --> H8
    %% class H1 pending;

    %% From footstep wavelet
    D --> I1 
    D --> I4
    subgraph Math: Fall 2025
        I1[filter]
        I2[X Location]
        I3[X, Z Location with camera move]
        I4[Complex Version of FootStep Wavelet]
    end
    H3 --> I2
    I2 --> I3


    H8 --> J1
    F1 --> J1
    subgraph Josh ENGR 898: Federated Learning
        J1
    end

    H8 --> K1
    F1 --> K1
    subgraph FootStep Features
        K1[Use Object detection: e.x. YOLO]
    end

    I2 -->L1
    subgraph Stride Features
        L1[Use Transformer?]
    end

    X1[camera track walker]
    X2[anonomize on camera]
    x3[sterio camera]

    %% Phase 7 - Output
    Z[FIN]
    L1 --> Z
    K1 --> Z

    class Z shared;